In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [ ]:
from subprocess import check_output
#print(check_output(["ls", "../input"]).decode("utf8"))

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn import preprocessing
from sklearn.model_selection import train_test_split # to split the data into two parts
%matplotlib inline
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv("https://raw.githubusercontent.com/mhmmd-nauman/DataSets/master/wdbc/csv/wdbc-complete.csv",header = 0)

In [ ]:
df.head()

   Mean Radius  Mean Texture  ...  Worst Fractal Dimension  Diagnosis
0        17.99         10.38  ...                  0.11890          M
1        20.57         17.77  ...                  0.08902          M
2        19.69         21.25  ...                  0.08758          M
3        11.42         20.38  ...                  0.17300          M
4        20.29         14.34  ...                  0.07678          M

[5 rows x 31 columns]

In [ ]:
#df.drop('id',axis=1,inplace=True)
#df.drop('Unnamed: 32',axis=1,inplace=True)

In [ ]:
#df['Offered'] = df['Offered'].map({'Yes':1,'No':0})
#df['Application Status'] = df['Application Status'].map({'Complete':1,'NotComplete':0})
from sklearn.preprocessing import LabelEncoder
labelencoder_X_1 = LabelEncoder()
#df['Application Status'] = labelencoder_X_1.fit_transform(df['Application Status'])
#df['Domicile'] = labelencoder_X_1.fit_transform(df['Domicile'])
#df['Gender'] = labelencoder_X_1.fit_transform(df['Gender'])
#df['Province'] = labelencoder_X_1.fit_transform(df['Province'])
df['Diagnosis'] = labelencoder_X_1.fit_transform(df['Diagnosis'])

In [ ]:
df.head()

   Mean Radius  Mean Texture  ...  Worst Fractal Dimension  Diagnosis
0        17.99         10.38  ...                  0.11890          1
1        20.57         17.77  ...                  0.08902          1
2        19.69         21.25  ...                  0.08758          1
3        11.42         20.38  ...                  0.17300          1
4        20.29         14.34  ...                  0.07678          1

[5 rows x 31 columns]

In [ ]:
data_df= list(df.columns[0:30]) 
data_df_main = df.loc[:,data_df]

In [ ]:
data_df_main

     Mean Radius  Mean Texture  ...  Worst Symmetry  Worst Fractal Dimension
0          17.99         10.38  ...          0.4601                  0.11890
1          20.57         17.77  ...          0.2750                  0.08902
2          19.69         21.25  ...          0.3613                  0.08758
3          11.42         20.38  ...          0.6638                  0.17300
4          20.29         14.34  ...          0.2364                  0.07678
..           ...           ...  ...             ...                      ...
564        21.56         22.39  ...          0.2060                  0.07115
565        20.13         28.25  ...          0.2572                  0.06637
566        16.60         28.08  ...          0.2218                  0.07820
567        20.60         29.33  ...          0.4087                  0.12400
568         7.76         24.54  ...          0.2871                  0.07039

[569 rows x 30 columns]

In [ ]:
X = data_df_main
y = df['Diagnosis']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,
                                                   y,
                                                   test_size=0.3,
                                                   random_state=0)

In [ ]:
svm_model = SVC()

parameters = [
              {'C': [1, 10, 100], 
               'kernel': ['linear']
              },
              
 ]

In [ ]:
grid_svm = GridSearchCV(svm_model, parameters, cv=20, scoring="accuracy")
grid_svm.fit(X_train,y_train)

GridSearchCV(cv=20, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [1, 10, 100], 'kernel': ['linear']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=0)

In [ ]:
print(grid_svm.best_score_)

0.9598684210526314

In [ ]:
y_pred = grid_svm.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_pred)
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
Sp = tn / (tn+fp)
Sn = tp/(tp + fn)

In [ ]:
print(cm)
print(Sp)
print(Sn)

[[102   6]
 [  2  61]]
0.9444444444444444
0.9682539682539683

In [ ]:
from sklearn.metrics import cohen_kappa_score
cohen_score = cohen_kappa_score(y_test, y_pred)

In [ ]:
cohen_score

0.8594069529652352